### ISSUE TITLE
Error running Filezilla download recipe

### ISSUE THREAD

**Issue by everetteallen** [grahampugh/recipes#3]
com.github.grahampugh.recipes.download.FileZilla 
bad escape \p at position 2
Failed.
macOS 10.15.7
/Library/AutoPkg/Python3/Python.framework/Versions/Current/bin/python3 --version              
Python 3.7.5

**Comment by everetteallen** [comment]
Here is the sanitized  verbose output:
=====

autopkg run com.github.grahampugh.recipes.download.FileZilla -vvv
Processing com.github.grahampugh.recipes.download.FileZilla...
WARNING: com.github.grahampugh.recipes.download.FileZilla is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
{'API_PASSWORD': 'uwish',
 'API_USERNAME': 'uwish',
 'AUTOPKG_VERSION': '2.3.1',
 'FAIL_RECIPES_WITHOUT_TRUST_INFO': False,
 'GIT_PATH': '/usr/bin/git',
 'JSS_REPOS': [{'type': 'CDP'}],
 'JSS_URL': 'https://nc.jamfcloud.com:443/',
 'JSS_VERIFY_SSL': True,
 'NAME': 'FileZilla',
 'PARENT_RECIPES': [],
 'RECIPE_CACHE_DIR': '/Users/user/Library/AutoPkg/Cache/com.github.grahampugh.recipes.download.FileZilla',
 'RECIPE_DIR': '/Users/user/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahampugh-recipes/FileZilla',
 'RECIPE_OVERRIDE_DIRS': ['~/Library/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': '/Users/user/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahampugh-recipes/FileZilla/FileZilla-stable.download.recipe',
 'RECIPE_REPOS': {'/Users/user/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahampugh-recipes': {'URL': 'https://github.com/autopkg/grahampugh-recipes.git'},
                  '/Users/user/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes': {'URL': 'https://github.com/autopkg/recipes.git'},
                  '/Users/user/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes': {'URL': 'https://github.com/autopkg/rtrouton-recipes.git'},
                  '/Users/user/Library/AutoPkg/RecipeRepos/com.github.everetteallen.ega-recipes': {'URL': 'https://github.com/everetteallen/ega-recipes.git'},
                  '/Users/user/Library/AutoPkg/RecipeRepos/com.github.hjuutilainen.autopkg-virustotalanalyzer': {'URL': 'https://github.com/hjuutilainen/autopkg-virustotalanalyzer.git'}},
 'RECIPE_SEARCH_DIRS': ['.',
                        '~/Library/AutoPkg/Recipes',
                        '/Library/AutoPkg/Recipes',
                        '/Users/user/Library/AutoPkg/RecipeRepos/com.github.hjuutilainen.autopkg-virustotalanalyzer',
                        '/Users/user/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahampugh-recipes',
                        '/Users/user/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes',
                        '/Users/user/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes',
                        '/Users/user/Library/AutoPkg/RecipeRepos/com.github.everetteallen.ega-recipes'],
 'SEARCH_URL': 'https://filezilla-project.org/download.php?show_all=1',
 'STOPPROCESSINGIF_PREDICATE': 'download_changed == FALSE',
 'verbose': 3}
URLTextSearcher
{'Input': {'re_pattern': '\\<\\p\\>The latest stable version of FileZilla '
                         'Client is (?P<dl_version>.*)\\<\\/p\\>',
           'result_output_var_name': 'dl_version',
           'url': 'https://filezilla-project.org/download.php?show_all=1'}}
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 122, in main
    groupmatch, groupdict = self.re_search(content)
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 105, in re_search
    re_pattern = re.compile(self.env["re_pattern"], flags=self.prepare_re_flags())
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/re.py", line 234, in compile
    return _compile(pattern, flags)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/sre_parse.py", line 924, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/sre_parse.py", line 420, in _parse_sub
    not nested and not items))
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/sre_parse.py", line 501, in _parse
    code = _escape(source, this, state)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/sre_parse.py", line 402, in _escape
    raise source.error("bad escape %s" % escape, len(escape))
re.error: bad escape \p at position 2
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
bad escape \p at position 2
Failed.
Receipt written to /Users/user/Library/AutoPkg/Cache/com.github.grahampugh.recipes.download.FileZilla/receipts/com.github.grahampugh.recipes.download-receipt-20210318-133025.plist

The following recipes failed:
    com.github.grahampugh.recipes.download.FileZilla
        Error in com.github.grahampugh.recipes.download.FileZilla: Processor: URLTextSearcher: Error: bad escape \p at position 2


=====
